[tools]
go = [
  "1.22.1",
  "1.21.8",
  "1.20.14",
]

java = [
  'openjdk-17.0.2',
  'openjdk-21.0.1',
  'oracle-17.0.9',
  'oracle-21.0.1',
  'adoptopenjdk-17.0.9+9',
  'adoptopenjdk-21.0.1+12.0.LTS', # comment out after installing all these tools
  'adoptopenjdk-11.0.21+9',
  '17.0.2',
  '21.0.1',
]

protoc = [
  '26.1',
  '25.3',
]

protoc-gen-go-grpc = [
  '1.3.0'
]

protoc-gen-go = [
  '1.33.0'
]

postgres = [
  '16.2',
  '15.6',
]

gradle = [ '8.6' ]

scala = [
  '3.4.0',
]

kotlin = [
  '1.9.22',
]

[env]
CGO_ENABLED = '1'
