"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true

[[plugin.append_previewers]]
mime = "text/csv"
run  = "miller"

[[plugin.append_previewers]]
name = "*"
run  = "hexyl"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
