[tools]
go = [
  "1.22.4",
  "1.21.11",
  "1.20.14",
]

java = [
  'oracle-graalvm-21.0.2',
  'oracle-graalvm-17.0.10',
  'oracle-21.0.2',
  'oracle-17.0.10',
  'adoptopenjdk-21.0.3+9.0.LTS',
  'adoptopenjdk-17.0.11+9',
  'adoptopenjdk-11.0.23+9',
  'adoptopenjdk-8.0.412+8',
]

protoc = [
  '27.1',
  '26.1',
]

gradle = '8.8'

scala = '3.5.0'
scala-cli = "1.5.0"

kotlin = [
  '2.0.0',
  '1.9.22',
]

gleam = "1.2.0"
erlang = "27.0"

dotnet-core = "8.0.302"

[env]
CGO_ENABLED = '0'

[settings]
verbose = false
jobs = 16
