[tools]
go = [
  "1.22.1",
  "1.21.8",
  "1.20.14",
]

java = [
  'openjdk-17.0.2',
  'openjdk-21.0.2',
  'openjdk-11.0.2',
  'oracle-17.0.10',
  'oracle-21.0.2',
  'adoptopenjdk-17.0.10+7',
  'adoptopenjdk-21.0.2+13.0.LTS',
  'adoptopenjdk-11.0.22+7',
  'adoptopenjdk-8.0.402+6',
  '17.0.2',
  '21.0.2',
  '11.0.2',
]

protoc = [
  '27.0',
  '26.1',
]

postgres = [
  '16.2',
  '15.6',
]

gradle = [ '8.6' ]

scala = [
  '3.4.0',
]

kotlin = [
  '1.9.22',
]

[env]
CGO_ENABLED = '0'
