[tools]
go = [
  "1.22.4",
  "1.21.11",
  "1.20.14",
]

java = [
  'openjdk-17.0.2',
  'openjdk-21.0.2',
  'openjdk-11.0.2',
  'oracle-17.0.10',
  'oracle-21.0.2',
  'oracle-graalvm-17.0.10',
  'oracle-graalvm-21.0.2',
  'adoptopenjdk-17.0.11+9',
  'adoptopenjdk-21.0.3+9.0.LTS',
  'adoptopenjdk-11.0.23+9',
  'adoptopenjdk-8.0.412+8',
  '17.0.2',
  '21.0.2',
  '11.0.2',
]

protoc = [
  '27.1',
  '26.1',
]

postgres = [
  '16.2',
  '15.6',
]

gradle = [ '8.8' ]

scala = [
  '3.4.2',
]

kotlin = [
  '2.0.0',
  '1.9.22',
]

[env]
CGO_ENABLED = '0'
